apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanbanboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kanbanboard-pod
  template:
    metadata:
      labels:
        app: kanbanboard-pod
    spec:
      containers:
        - name: kanbanboard
          image: 489455091964.dkr.ecr.ap-south-1.amazonaws.com/sabyainfrakanban:latest
          # imagePullPolicy: Never
          ports:
            - containerPort: 80
          