apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanbanboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kanbanboard-pod
  template:
    metadata:
      labels:
        app: kanbanboard-pod
    spec:
      containers:
        - name: kanbanboard
          image: anushapalle/infrasabyaanusha
          # imagePullPolicy: Never
          ports:
            - containerPort: 80
          # readinessProbe:
          #   httpGet:
          #     path: /readiness
          #     port: 3000
          #   initialDelaySeconds: 20
          #   periodSeconds: 3
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySeconds: 20
          #   periodSeconds: 3
          # env:
          #   - name: VERSION
          #     value: "4.0"